language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t 1earndocker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 1earndocker/docker-react npm run test

